name: Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No dependencies to install."

      - name: Print working directory
        run: pwd

      - name: Run the application
        env:
          MY_SECRET: ${{ secrets.GH_TOKEN }}  # Use the secret here
        run: |
          echo "Using secret..."
          # Example command using the secret
          # This command will not display the secret
          echo "The secret is set."
          python3 Github\ api.py
